spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:notesdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aplusbluenote@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: caffeine
    cache-names: emailCodes
    caffeine:
      spec: expireAfterWrite=5m,maximumSize=10000

jwt:
  expiration-hours: 12

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /v3/api-docs

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:your-bucket-name}
    presign-expiration-seconds: ${AWS_S3_PRESIGN_EXPIRATION_SECONDS:600}
